### ISSUE TITLE
Selecting a client index higher than what is already existing blocks the server

### ISSUE THREAD

**Issue by N-faycal** [buckyroberts/Python-Reverse-Shell#12]
turtle> list
----- Clients -----

```
turtle> select 10
Not a valid selection
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 141, in work
    start_turtle()
  File "server.py", line 65, in start_turtle
    target, conn = get_target(cmd)
TypeError: 'NoneType' object is not iterable
```

No command is accepted after this exception.

**Comment by N-faycal** [comment]
Corrected

turtle> list
----- Clients -----

turtle> select 10
Not a valid selection
turtle> select e
Client index should be an integer
turtle>
